### ISSUE TITLE
FPS, Exposure & ISO Values change on camera click

### ISSUE THREAD

**Issue by markmorris** [Rob2048/VectorONE#3]
Whenever I click a live camera, the settings on the left panel get changed. Assuming this is reading incorrect package data.

![Image](https://cdn.discordapp.com/attachments/293824445007790080/817073022426939432/Capture.PNG)

**Comment by Rob2048** [comment]
Did you find the cause of this?

**Comment by markmorris** [comment]
Not yet, I will be working on this again a bit later, so I will keep you updated if I find anything.

**Comment by czyz** [comment]
Was there every any movement on this? I'm tempted to try and build a few cameras myself for this as the tracking quality looks to possibly be very good, but I'm not sure how possible or not it is to get this working.

**Comment by Rob2048** [comment]
Hi @czyz, the tracking quality is quite good, but the project needs lots more work to be usable.
